version: '3'
services:
   logstash:
     image: docker.elastic.co/logstash/logstash:7.6.1
#     environment:
#       - PATH_CONFIG=/usr/share/logstash/pipeline/*.conf
#       - LOGSTASH_CONF=/usr/share/logstash/pipeline
     volumes:
       - $PWD/../pipelines:/pipelines
       - $PWD/../data/:/data
     depends_on:
       - elasticsearch
     networks: ['stack']
     command: echo "Should be started manually"

   elasticsearch:
     image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
     ports:
       - 9200:9200
     volumes:
       - data-volume:/usr/share/elasticsearch/data
     networks: ['stack']
     environment:
       - bootstrap.memory_lock=true
       - discovery.type=single-node
       - cluster.routing.allocation.disk.threshold_enabled=false
      
   kibana:
     image: docker.elastic.co/kibana/kibana:7.6.1
     links:
       - elasticsearch
     ports:
       - 5601:5601
     networks: ['stack']

volumes:
  data-volume:
    driver: local

networks:
  stack: {}
